server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:45432/catalog
    username: catalog
    password: changeme
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
  security:
    user:
      name: admin
      password: password
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: catalog
    liquibase-schema: catalog
    database-change-log-table: databasechangelog
    database-change-log-lock-table: databasechangeloglock


recommendation-service:
  url: "http://localhost:8085"

security:
  jwt:
    public-key-path: classpath:public.pem
